### ISSUE TITLE
Bug in the commit 8a52f3dc3fb695094f678cf5e36b7f97b99a0f31

### ISSUE THREAD

**Issue by giulianoiorio** [GiacobboNicola/IC4popsyn#5]
The commit 
commit 8a52f3dc3fb695094f678cf5e36b7f97b99a0f31 (HEAD)
Author: GNicola <giacobbo.nicola@gmail.com>
Date:   Mon Aug 2 09:29:35 2021 +0200

    total mass to test

introduced some kind of bug in the module. 

It seems that the generated masses are completely off with respect to the expected distribution. 
In particular, the masses are all very small (around 0.1 Msun), this is confirmed also by the plots generated by pytest (below).

I confirm that the previous commit works as expected

![bug](https://user-images.githubusercontent.com/19323635/150024454-8eb0c48d-a375-4741-a0ff-402bd7334b38.png)

**Comment by GiacobboNicola** [comment]
I fixed the bug (commit ca757763eb251440f25138f1eccd1a4e89cbd832) for the plot (below) but still some issue with the second test:
`chi, _ = chisquare(hist, y)`
the `scipy.stats.chisquare` has been updated (and there is a [know problem](https://github.com/UDST/synthpop/issues/75)). Did you perform the test with both commits on the same machine?

![testplot](https://user-images.githubusercontent.com/19323635/150030787-b945957f-8b1d-45eb-8b8d-180c3dca0b5b.png)

**Comment by giulianoiorio** [comment]
Thank you Nicola, 
I see the problem, it is just that mass_range is now called mass_ranges, **notice that the example.py should be also corrected for this**. This is very important since this file is "the entry point" for new module users. Indeed I found this problem helping a student that was trying to generate sevn ics following what written in example.py. I am pushing this  update with a new commit.
Concerning the other tests, they were successful on my office machine (scipy 1.6.2) while they fail in both commits on the student laptop (I guess his scipy version is more recent than min since it just recently installed python). I confirm that with this scipy version all the tests succeed   also for the new commit. 

Concerning the reason of the bug (change of name of a parameter), I think for the future we should use the practice to allow for the first new commits to use both the old and the parameters name raising a DepreactedWarning if the old names are used.

**Comment by GiacobboNicola** [comment]
Thank for updating the file. You are right, I completely forgot to check _example.py_.
I will look for a possible solution in the following days.

I agree with the idea of raising Deprecated/Warning for old names.

**Comment by giulianoiorio** [comment]
I think we can close the issue :)
