### ISSUE TITLE
Single star mode for sevn does not preserve mass limits

### ISSUE THREAD

**Issue by michelamapelli** [GiacobboNicola/IC4popsyn#9]
Just browsing this for a class and found that the SinglePop mode makes mass extremes wrong. Thank you for the code.

**Comment by giulianoiorio** [comment]
Hi, I suppose you are referring to the example.py. There was a typo in the example, the call to pop.Binaries wrongly used the parameter mass_range instead of mass_ranges. This is now fixes. 
Thank you for spotting this!
